service: electr-rest
frameworkVersion: '>=1.1.0 <2.0.0'
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
functions:
  AccountController-getMe:
    handler: dist/endpoints/AccountController.getMe
    events:
      - http:
          path: account/getMe
          method: get
          cors: true
  AccountController-signup:
    handler: dist/endpoints/AccountController.signup
    events:
      - http:
          path: signup
          method: get
          cors: true
  AccountController-login:
    handler: dist/endpoints/AccountController.login
    events:
      - http:
          path: login
          method: get
          cors: true
  AccountController-logout:
    handler: dist/endpoints/AccountController.logout
    events:
      - http:
          path: logout
          method: get
          cors: true
  AccountController-getAccountPage:
    handler: dist/endpoints/AccountController.getAccountPage
    events:
      - http:
          path: account/getAccountPage
          method: get
          cors: true
  AccountController-setAccountPage:
    handler: dist/endpoints/AccountController.setAccountPage
    events:
      - http:
          path: account/setAccountPage
          method: post
          cors: true
  AccountController-getFeed:
    handler: dist/endpoints/AccountController.getFeed
    events:
      - http:
          path: account/getFeed
          method: get
          cors: true
  AccountController-createDefaultAccount:
    handler: dist/endpoints/AccountController.createDefaultAccount
    events:
      - http:
          path: account/createDefaultAccount
          method: get
          cors: true
  AccountController-addAccount:
    handler: dist/endpoints/AccountController.addAccount
    events:
      - http:
          path: account/addAccount
          method: post
          cors: true
  AccountController-getAll:
    handler: dist/endpoints/AccountController.getAll
    events:
      - http:
          path: account/getAll
          method: get
          cors: true
  AccountController-runQuery:
    handler: dist/endpoints/AccountController.runQuery
    events:
      - http:
          path: runQuery
          method: post
          cors: true
  create:
    handler: oper/todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
  list:
    handler: oper/todos/list.list
    events:
      - http:
          path: todos
          method: get
          cors: true
  get:
    handler: oper/todos/get.get
    events:
      - http:
          path: 'todos/{id}'
          method: get
          cors: true
  update:
    handler: oper/todos/update.update
    events:
      - http:
          path: 'todos/{id}'
          method: put
          cors: true
  delete:
    handler: oper/todos/delete.delete
    events:
      - http:
          path: 'oper/todos/{id}'
          method: delete
          cors: true
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: '${self:service}-${opt:stage, self:provider.stage}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*'
resources:
  Resources:
    Sessions:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        TableName: electr-rest-us-east-1-Sessions
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
