service: electr-rest
frameworkVersion: '>=1.1.0 <2.0.0'
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
functions:
  create:
    handler: oper/todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
  list:
    handler: oper/todos/list.list
    events:
      - http:
          path: todos
          method: get
          cors: true
  get:
    handler: oper/todos/get.get
    events:
      - http:
          path: 'todos/{id}'
          method: get
          cors: true
  update:
    handler: oper/todos/update.update
    events:
      - http:
          path: 'todos/{id}'
          method: put
          cors: true
  delete:
    handler: oper/todos/delete.delete
    events:
      - http:
          path: 'oper/todos/{id}'
          method: delete
          cors: true
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: '${self:service}-${opt:stage, self:provider.stage}'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*'
resources:
  Resources:
    Sessions:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        TableName: electr-rest-us-east-1-Sessions
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
